name : Docker Torrent Download 
on : 
	workflow_dispatch:
		inputs:
			url:
				description : 'Torrent file URL'
				required: true
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader:latest
    steps:
    
        - name: Write .env File
          run: |
               echo '${{ secrets.DOTENV }}' >> .env
               
       - name: Download File
         run: node /app/download.js ${{ github.event.input.url }}
         
       - name: LS
         run: cd/data && ls -la
         
       - name: upload to Driver 
         run: node /app/upload.js
